# Generated by Django 5.0.1 on 2024-02-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_logo1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_logo2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
