# Generated by Django 4.1.12 on 2024-01-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_user_profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/dist/img/user'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_logo1',
            field=models.ImageField(blank=True, null=True, upload_to='static/dist/img/logo'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_logo2',
            field=models.ImageField(blank=True, null=True, upload_to='static/dist/img/logo'),
        ),
    ]
