# Generated by Django 5.0.1 on 2024-01-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_agency_agency_address_and_more'),
        ('user', '0004_alter_agency_agency_website'),
    ]

    operations = [
    ]
