# Generated by Django 4.2.9 on 2024-01-10 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_agency_agency_address_and_more'),
        ('user', '0004_alter_agency_agency_website'),
    ]

    operations = [
    ]
