# Generated by Django 4.1.12 on 2024-01-05 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=50)),
                ('ageny_address', models.CharField(max_length=50)),
                ('agency_head', models.CharField(max_length=50)),
                ('agency_contact', models.CharField(max_length=50)),
                ('agency_email', models.CharField(max_length=50)),
                ('agency_website', models.CharField(max_length=50)),
                ('agency_logo1', models.CharField(max_length=50)),
                ('agency_logo2', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=50)),
                ('office_head', models.CharField(max_length=50)),
                ('office_description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_agency_name', to='tracking.agency')),
            ],
        ),
    ]
