# Generated by Django 5.0.1 on 2024-01-24 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='urgency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_attachment', to='user.agency'),
        ),
        migrations.AddField(
            model_name='document',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_of_document', to='tracking.category'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_attachment', to='tracking.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_flow_name', to='tracking.flow'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tracking', to='tracking.document'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='office_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_user_tracking', to='user.office_user'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_tracking', to='tracking.status'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='flow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_workflow', to='tracking.flow'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='office_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_workflow', to='user.office'),
        ),
    ]
