# Generated by Django 4.1.12 on 2024-01-09 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='office_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_workflow', to='user.office'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tracking', to='tracking.document'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='office_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_user_tracking', to='user.office_user'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_tracking', to='tracking.status'),
        ),
        migrations.AddField(
            model_name='document',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_of_document', to='tracking.category'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='agency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_attachment', to='user.agency'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_attachment', to='tracking.document'),
        ),
    ]
