# Generated by Django 5.0.1 on 2024-02-07 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='urgency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_attachment', to='user.agency'),
        ),
        migrations.AddField(
            model_name='document',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_of_document', to='tracking.category'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_attachment', to='tracking.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_flow_name', to='tracking.flow'),
        ),
        migrations.AddField(
            model_name='forwarded',
            name='document_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_document', to='tracking.document'),
        ),
        migrations.AddField(
            model_name='forwarded',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward_from_office', to='user.office'),
        ),
        migrations.AddField(
            model_name='forwarded',
            name='forwarded_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_to_office', to='user.office'),
        ),
        migrations.AddField(
            model_name='received',
            name='document_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_doc', to='tracking.forwarded'),
        ),
        migrations.AddField(
            model_name='received',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_office', to='user.office'),
        ),
        migrations.AddField(
            model_name='received',
            name='received_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_office', to='user.office'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tracking', to='tracking.document'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='flow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_workflow', to='tracking.flow'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='office_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_workflow', to='user.office'),
        ),
    ]
