# Generated by Django 5.0.1 on 2024-01-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='agency_id',
            new_name='urgency',
        ),
    ]
