# Generated by Django 5.0.1 on 2024-01-24 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forwarded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('received', models.BooleanField(default=False)),
                ('document_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_document', to='tracking.document')),
                ('forwarded_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_from_office', to='user.office')),
                ('forwarded_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_to_office', to='user.office')),
            ],
        ),
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('document_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_doc', to='tracking.forwarded')),
            ],
        ),
    ]
