# Generated by Django 5.0.1 on 2024-01-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_forwarded_forwarded_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_code',
            field=models.CharField(default='b66b2b5c34d74b7f881a3895619ef8b7', max_length=50, unique=True),
        ),
    ]
