# Generated by Django 5.0.1 on 2024-01-24 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_forwarded_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_of_document', to='tracking.category'),
        ),
        migrations.AlterField(
            model_name='document',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_flow_name', to='tracking.flow'),
        ),
    ]
