# Generated by Django 5.0.1 on 2024-02-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_model2_field1_alter_model2_field2'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwarded',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
